version: '3'

services:
  broker:
    image: eclipse-mosquitto:latest
    container_name: broker
    restart: always
    ports:
      - 1883:1883
    networks:
      - front_net
      - back_net

  nodered:
    image: nodered/node-red-docker
    container_name: nodered
    restart: always
    ports:
      - 1880:1880
    volumes:
      - nodered_data:/data
    networks:
      - front_net
      - back_net
    depends_on:
      - broker

  web:
    image: edge_agent_img
    container_name: edge_agent
    restart: always
    env_file:
    - ./edge_agent/env_vars/app.sh
    - ./edge_agent/env_vars/postgres_compose.sh
    ports:
      - 5000:5000
    networks:
      - front_net
      - back_net
    depends_on:
      - db
      
  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: iotwin
      POSTGRES_DB: iot_data
    ports:
      - 6000:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - back_net

volumes:
  db_data:
  nodered_data:  

networks:
  front_net:
  back_net: